### ISSUE TITLE
Error: Cannot find module 'lib' in require stack...

### ISSUE THREAD

**Issue by MarcBouteiller** [camunda/camunda-8-js-sdk#114] opened 2024-04-05 15:41 UTC
Hi ! I know this version is in alpha, but I wanted to submit my issue in case of.
An error is thrown when starting a NestJS project with camunda8/sdk@8.5.0-alpha.3 or camunda8/sdk@8.5.0-alpha.4

```
Error: Cannot find module 'lib'
Require stack:
- /home/xxx/workspace/projects/edl/poc/camunda/node_modules/.pnpm/@camunda8+sdk@8.5.0-alpha.4/node_modules/@camunda8/sdk/dist/admin/lib/AdminApiClient.js
- /home/xxx/workspace/projects/edl/poc/camunda/node_modules/.pnpm/@camunda8+sdk@8.5.0-alpha.4/node_modules/@camunda8/sdk/dist/admin/index.js
- /home/xxx/workspace/projects/edl/poc/camunda/node_modules/.pnpm/@camunda8+sdk@8.5.0-alpha.4/node_modules/@camunda8/sdk/dist/index.js
- /home/xxx/workspace/projects/edl/poc/camunda/dist/process.service.js
- /home/xxx/workspace/projects/edl/poc/camunda/dist/app.controller.js
- /home/xxx/workspace/projects/edl/poc/camunda/dist/app.module.js
- /home/xxx/workspace/projects/edl/poc/camunda/dist/main.js
```

## SDK Component
All

## Expected Behavior
The 'lib' is found

## Current Behavior
The 'lib' is not found

## Possible Solution
the path of 'lib' (or any other require() in the compiled js) seems to target a file in a same folder.

## Steps to Reproduce
1. nest new my-project
2. Call the camunda8 constructor anywhere  (ex: const camunda  = new Camunda8() in the controller)
3. npm run start:dev

## Context (Environment)
NodeJS 20
NestJS@10 project
PNPM

**Comment by jwulf** [comment] 2024-04-06 22:41
Thanks for reporting this. I know that alpha.3 had this issue. Let me reproduce it with alpha.4

**Comment by jwulf** [comment] 2024-04-07 09:22
This is due to the way that the package is structured in TypeScript, see here: https://github.com/camunda/camunda-8-js-sdk/issues/110

Two things: first of all, to solve this, I am taking out the module mapping and using explicit relative paths in the source, to avoid complicated transpilation configuration. 

Secondly: all the tests in CI are running using `ts-jest`, which means they prove the code _before_ it is transpiled. To address this, and make sure that transpilation and packaging issues which are not caught by the current test suite don't get through, I am adding to the CI testing an `npm build` step followed by a test run using the transpiled code in `dist` and the `package.json` entry point.  This simulates as close as possible the code that will be installed by `npm i` when the package is installed, and will catch issues of this class this before they hit NPM.

**Comment by jwulf** [comment] 2024-04-07 21:35
I've released alpha.5 which addresses this. 

Now, I will write the tests to make sure that we catch issues of this class before a package gets released.

**Comment by jwulf** [comment] 2024-04-08 01:05
alpha.6 includes the smoke test step, and also fixes an issue where instantiating a Camunda8 object with OAuth disabled would throw an error.

**Closed by jwulf** 2024-04-08 01:05 UTC

**Comment by MarcBouteiller** [comment] 2024-04-08 07:24
Thanks for you work !
